package dev.parseforge.domain.exception;

public enum ErrorCode {
    FORMAT_UNSUPPORTED,
    PDF_INVALID,
    FILE_INACCESSIBLE,
    DISK_SPACE_LOW,
    ENGINE_NOT_INSTALLED,
    ENGINE_CORRUPTED,
    PROCESS_START_FAILED,
    PROCESS_TIMEOUT,
    PROCESS_CRASHED,
    OUTPUT_NOT_CREATED,
    PERMISSION_DENIED,
    USER_CANCELLED
}
